BCM/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("<slug:country>/login", views.CountryLogin.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(next_page="index_redirect"), name="logout"),
    path("<slug:country>/signup", views.RegisterUser.as_view(), name="signup"),
    #path("<slug:country>/<slug:pk>/profile",views.ProfileView.as_view(), name="profile"),
    path("<slug:country>/", views.index, name="index"),
    path("<slug:country>/after_login", views.after_login, name="after_login"),
    path("accounts/login/", views.index_redirect),
    path("", views.index_redirect, name="index_redirect"),
]

BCM_multihosted/urls.py
from django.contrib import admin
from django.urls import include, path

from gs1ie.views import account_create_or_update, api_auth
from users.views import profile

urlpatterns = [
    path('API/v1/AccountCreateOrUpdate/', account_create_or_update),
    path('API/v1/auth/<token>/', api_auth, name='api_auth_v1'),
    path('profile/', profile, name='profile'),
    path('gs1ie/', include('gs1ie.urls')),
    path('prefixes/', include('prefixes.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path("", include("BCM.urls")),
]

gs1ie/urls.py
from django.urls import path

from . import views

app_name = 'gs1ie'
urlpatterns = [
    path('AccountCreateOrUpdate/', views.account_create_or_update, name='account_create_or_update'),
]

BCM/models.py
import random

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext as _


'''
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.SlugField(primary_key=True)

    # other info like firstname, surname and other stuff
    language = models.ForeignKey("Language", on_delete=models.CASCADE, null=True)  # ?

    @property
    def member_organisation(self):
        return self.user.member_organisations_memberorganisation.first()

    @property
    def company_organisation(self):
        return self.user.company_organisations_companyorganisation.first()

    @property
    def country(self):
        return self.user.member_organisations_memberorganisation.first().country

    class Meta:
        verbose_name_plural = _("User profiles")


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance, username=instance.username)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    profile_exist = Profile.objects.filter(user=instance).first()
    if profile_exist:
        instance.profile.save()
    else:
        kwargs.pop("created")
        create_user_profile(sender, instance, created=True, **kwargs)
'''

class Country(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=2)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = _("Countries")

    def __str__(self):
        return "{} ({})".format(self.name, self.slug)

    def get_default_language(self):
        default_lang = LanguageByCountry.objects.filter(
            country=self, default=True).first()
        if default_lang:
            return default_lang
        else:
            return random.choice(LanguageByCountry.objects.filter(country=self))


class Language(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=2)

    def __str__(self):
        return "{} ({})".format(self.name, self.slug)


class LanguageByCountry(models.Model):
    country = models.ForeignKey("Country", on_delete=models.CASCADE)
    language = models.ForeignKey("Language", on_delete=models.CASCADE)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = _("Languages by countries")

    def __str__(self):
        return "{}_{}".format(self.country.slug, self.language.slug)

    def save(self):
        if self.default:
            queryset = LanguageByCountry.objects.filter(
                country=self.country, default=True).exclude(id=self.id).all()
            for record in queryset:
                record.default = False
                record.save()
        super(LanguageByCountry, self).save()

BCM/views.py
# we use 100 characters line length, isn't it?
from django.shortcuts import render, redirect, reverse

# from BCM.decorators import set_language_by_country, set_language_by_user, set_language_by_auto
from . import models
# import django.utils.translation as trans
from django.contrib.auth import views as auth_views
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from django.contrib.auth import authenticate, login
# from django.utils.decorators import method_decorator


# @set_language_by_auto
def index_redirect(request):
    # country = "__"
    # if request.method == "POST":
    #     country = request.POST.get("country")
    #     country_obj = models.Country.objects.filter(slug=country).first()
    #     # lang = country_obj.get_default_language()
    #     # set_language(lang.language.slug, request)
    #     return redirect(reverse('index', args=[country]))
    # else:
    #     countries = models.Country.objects.all()

    countries = models.Country.objects.all()
    return render(request, "bcm/generic.html", {"countries": countries})


# @set_language_by_auto
def index(request, country):
    # langs = models.LanguageByCountry.objects.filter(country__slug=country)
    # set_language_by_country(request, country)
    countries = models.Country.objects.all()
    return render(request, 'bcm/generic.html', {"countries": countries})

@login_required
# @set_language_by_auto
def after_login(request, country):
    # set_language_by_user(request, country)
    return redirect("profile", pk=request.user.username, country=country)

class CountryLogin(auth_views.LoginView):
    template_name = 'bcm/registration/login.html'

    # @method_decorator(set_language_by_auto)
    def dispatch(self, request, *args, **kwargs):
        self.country = kwargs.get("country")
        return super(CountryLogin, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["country"] = self.country
        context["next"] = "after_login"
        return context

'''
class ProfileView(LoginRequiredMixin, UpdateView):
    model = models.Profile
    template_name = "bcm/profile.html"
    fields = ["country", "language"]
    success_url = "profile"

    # @method_decorator(set_language_by_auto)
    def dispatch(self, request, *args, **kwargs):
        # self.country = kwargs.get("country")
        self.username = request.user.username
        # set_language_by_user(request, self.country)
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["country"] = self.country
        return context
'''

class RegisterUser(CreateView):
    model = User
    template_name = "bcm/registration/registration.html"
    form = UserCreationForm
    fields = "__all__"

    # @method_decorator(set_language_by_country)
    def dispatch(self, request, *args, **kwargs):
        self.country = kwargs.get("country")
        # self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["country"] = self.country
        return context

    def get_form_class(self):
        return UserCreationForm

    def get_success_url(self):
        self.username = self.object.username
        login(self.request, self.object)
        return reverse("profile", args=(self.country, self.object.username))

BCM/templates/bcm/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.bundle.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-dark bg-dark">
		<span class="navbar-brand mb-0 h1">{% trans 'Django translations' %}</span>
		{% if user.is_authenticated %}
		<a href="{% url 'profile' country=country pk=user.username %}">{% trans 'Profile' %}</a>
		<a href="{% url 'logout' %}">{% trans 'Logout' %}</a>
		{% else %}
		<a href="{% url 'login' country=country%}">{% trans 'Login' %}</a>
		<a href="{% url 'signup' country=country%}">{% trans 'Register' %}</a>
		{% endif %}
	</nav>
	{% block content%}
	{% endblock %}


    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

BCM/templates/bcm/generic.html
{% extends 'bcm/new_base.html' %}
{% load i18n %}
{% block content %}
    {% comment %}
    <h1>{% trans "Choose your country" %}</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <select name="country">
            {% for country in countries %}
            <option value={{country.slug}}>{{country.name}}</option>
            {% endfor %}
        </select>
        <input type="submit" name="Submit">
    </form>
    {% endcomment %}

    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="welcome-title">{% trans 'Welcome' %}</h2>
            </div>
        </div>
    </div>
    <div class="row welcome-navigation">
        <div class="col welcome-left-column">
            <div class="welcome-column-content">
            {% for country in countries %}
                <p>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'profile' %}">{{ country.slug }} {% trans 'Admin Profile' %}</a>
                    {% else %}
                        <a href="{% url 'login' country=country.slug %}">{{ country.slug }} {% trans 'Admin Login' %}</a> |
                        <a href="{% url 'signup' country=country.slug %}">{{ country.slug }} {% trans 'Admin Register' %} </a>
                    {% endif %}
                </p>
            {% endfor %}
            </div>
        </div>
        <div class="col welcome-right-column">
            <div class="welcome-column-content">
                <a href="{% url 'gs1ie:account_create_or_update' %}">{% trans 'API Account Create or Update' %}</a>
            </div>
        </div>
    </div>

{% endblock %}

BCM/templates/bcm/index.html
{% extends 'bcm/new_base.html' %}
{% load i18n %}
{% block content %}
	{% get_current_language as LANGUAGE_CODE %}
	<!-- Current language: {{ LANGUAGE_CODE }} -->
	<h1>{% trans "Choose your language" %}</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <select name="language">
            {% for language in languages %}
            <option value={{language.language.slug}}>{{language.language.name}}</option>
            {% endfor %}
        </select>
        <input type="submit" name="Submit">
    </form>
{% endblock %}

BCM/templates/bcm/new_base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>BCM Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'site/css/bcm.css' %}">
</head>

<body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">BCM</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!--
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 1</a>
                </li>
                -->
            </ul>

            <ul class="navbar-nav mr-md-2 justify-content-end">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                       id="navbar-languages" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        {% trans 'Languages' %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbar-languages">
                        {% for language_by_country in user.profile.country.languagebycountry_set.all %}
                            <a class="dropdown-item"
                               href="{{ request.path }}?new_language={{ language_by_country.language.slug }}">
                                {{ language_by_country.language }}
                            </a>
                        {% endfor %}
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

BCM/templates/bcm/profile.html
{% extends 'bcm/new_base.html' %}
{% load i18n %}
{% block content %}
<h1>{% trans 'User profile' %}</h1>
<form action="" method="POST">
	{% csrf_token %}
{{form}}
<input type="submit" name="" value="{% trans 'Submit' %}"/>
</form>
{% endblock %}