BCM/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("<slug:country>/login", views.CountryLogin.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(next_page="index_redirect"), name="logout"),
    path("<slug:country>/signup", views.RegisterUser.as_view(), name="signup"),
    #path("<slug:country>/<slug:pk>/profile",views.ProfileView.as_view(), name="profile"),
    path("<slug:country>/", views.index, name="index"),
    path("<slug:country>/after_login", views.after_login, name="after_login"),
    path("accounts/login/", views.index_redirect),
    path("", views.index_redirect, name="index_redirect"),
]

BCM_multihosted/urls.py
from django.contrib import admin
from django.urls import include, path

from gs1ie.views import account_create_or_update, api_auth
from users.views import profile

urlpatterns = [
    path('API/v1/AccountCreateOrUpdate/', account_create_or_update),
    path('API/v1/auth/<token>/', api_auth, name='api_auth_v1'),
    path('profile/', profile, name='profile'),
    path('gs1ie/', include('gs1ie.urls')),
    path('prefixes/', include('prefixes.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path("", include("BCM.urls")),
]

prefixes/urls.py
from django.urls import path

from . import views

app_name = 'prefixes'
urlpatterns = [
    path('', views.prefixes_list, name='prefixes_list'),
    path('ajax/', views.prefixes_ajax),
    path('prefixes_set_starting/<int:prefix_id>', views.prefixes_set_starting, name='prefixes_set_starting'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('products_add_product', views.products_add_product, name='products.add_product'),
    path('products_products_list', views.products_products_list, name='products.products_list'),
    path('static_views_terms', views.static_views_terms, name='static_views.terms'),
    path('prefixes_prefixes_list', views.prefixes_prefixes_list, name='prefixes.prefixes_list'),
    path('auth_profile', views.auth_profile, name='auth_profile'),
    path('excel_export_select', views.excel_export_select, name='excel.export_select'),
    path('excel_import_file', views.excel_import_file, name='excel.import_file'),
    path('locations_locations_list', views.locations_locations_list, name='locations.locations_list'),
]

prefixes/forms.py
from django import forms


class PrefixActionForm(forms.Form):
    select_prefix = forms.ChoiceField(widget=forms.RadioSelect) #, choices=(
    #    ('1','539123123'),
    #    ('5','53900012'),
    #    ('6','53900011')
    #))
    prefix_action = forms.ChoiceField(widget=forms.RadioSelect, choices=(
        # item actions
        ('new_product', 'New Product'),
        ('starting_gtin', 'Starting GTIN'),
        ('set_this', 'Set this active'),
        ('first_available', 'Set to first available'),
        ('export_available', 'Export available GTINs'),

        # location actions
        ('new_gln', 'New Location'),
        ('starting_gln', 'Starting GLN'),
        ('set_this_gln', 'Set this active'),
        ('first_available_gln', 'Set to first available'),
        ('export_available_gln', 'Export available GTINs') )
    )


class StartingNumberForm(forms.Form):
    starting_number = forms.CharField(label='New Starting number', required=True)

prefixes/views.py
import tempfile
import json
from zipfile import ZipFile
from openpyxl import load_workbook
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, reverse
from django.conf import settings
from core import flash, flash_get_messages
from services import prefix_service, users_service, product_service
from .forms import PrefixActionForm, StartingNumberForm
from products.models import Product
from barcoding.utilities import normalize


def prefixes_list(request):
    current_user = request.user
    company_organisation = users_service.get_company_organisation(current_user)

    prefixes = prefix_service.all()
    susp_prefixes = prefix_service.find(company_organisation=company_organisation, is_suspended=True).all()

    '''
    prefixes = prefix_service.find_all().all()
    result = db.session.query('prefix', 'products'). \
        from_statement(text("select products.gs1_company_prefix as prefix, 
                                    count(*) as products
                             from products
                             where owner_id=%s
                             group by products.gs1_company_prefix" % current_user.id)).all()

    result_locations = db.session.query('prefix', 'locations'). \
        from_statement(text("select locations.gs1_company_prefix as prefix, 
                                    count(*) as locations
                             from locations
                             where owner_id=%s
                             group by locations.gs1_company_prefix" % current_user.id)).all()

    # set products count
    for prefix in prefixes:
        for row in result:
            if prefix.prefix == row[0]:
                setattr(prefix, 'products', row[1])

    # set locations count
    for prefix in prefixes:
        for row in result_locations:
            if prefix.prefix == row[0]:
                setattr(prefix, 'locations', row[1])
    '''

    if request.method == 'POST':
        form = PrefixActionForm(request.POST)
        form.fields['select_prefix'].choices = [(str(p.id), p.prefix) for p in prefixes]
        if form.is_valid():
            try:
                int_prefix_id = int(form.data['select_prefix'])
            except (ValueError, TypeError):
                flash(request, 'Your selections were not valid!', 'danger')
            else:
                prefix = prefix_service.get(int_prefix_id)
                if not prefix:
                    raise Http404('Prefix not found')

                if prefix.is_special == 'READ-ONLY' and form.data['prefix_action'] != 'set_this':
                    flash(request, 'Read-only prefix, please contact GS1 helpdesk.', 'danger')
                else:
                    prefix_service.make_active(prefix.id)

                    prefix_action = form.data['prefix_action']
                    # Enter a new product in selected range
                    if prefix_action == 'new_product':
                        return redirect(reverse('user:products.add_product') + '?prefix=' + str(prefix.prefix))

                    # Set selected range as active and go to My Products
                    elif prefix_action == 'set_this':
                        return redirect(reverse('user:products.products_list'))

                    # Set starting GTIN in selected range manually
                    elif prefix_action == 'starting_gtin':
                        return redirect(reverse('prefixes:prefixes_set_starting', args=(prefix.id,)))

                    # Set starting GTIN to first available number
                    elif prefix_action == 'first_available':
                        try:
                            prefix.make_starting_from()
                        except Exception as e:
                            return render(request, 'prefixes/prefix_exhausted.html',
                                                   {'current_user': current_user, 'prefix': prefix })
                        prefix_service.save(prefix)
                        flash(request, 'Starting gtin has been set to GTIN-%s' % prefix.starting_from, 'success')
                        return redirect(reverse('prefixes:prefixes_list'))

                    # new location
                    elif prefix_action == 'new_gln':
                        return redirect(reverse('user:locations.add_location') + '?prefix=' + str(prefix.prefix))

                    elif prefix_action == 'first_available_gln':
                        pass
                        '''
                        try:
                            prefix.make_starting_from_gln()
                        except Exception,e:
                            return render_template('prefixes/prefix_exhausted.html', prefix=prefix)
                        prefix_service.save(prefix)
                        return redirect(url_for('.prefixes_list'))
                        '''

                    # Export available GTINs in this range
                    elif prefix_action == 'export_available':
                        try:
                            products = ( Product.objects.filter(owner = current_user)
                                                        .filter(gs1_company_prefix = prefix.prefix)
                                                        .order_by('gtin') )
                            prfxs = prefix.get_available_gtins(products)
                            if len(prfxs) > 0:
                                tfile = tempfile.NamedTemporaryFile(suffix='.xlsx')
                                zfile = tempfile.NamedTemporaryFile(suffix='.zip')

                                file_xlsx = load_workbook(settings.PREFIXES_EXCEL_TEMPLATE)
                                ws = file_xlsx.active
                                for index, prfx in enumerate(prfxs):
                                    _ = ws.cell(column=2, row=index + 5, value=prfx)
                                file_xlsx.save(filename=tfile.name)

                                with ZipFile(zfile.name, "w") as z:
                                    export_filename = "export_%s_available.xlsx" % (prefix.prefix,)
                                    attachment_filename = "export_%s_available.%s" % (prefix.prefix, 'zip')
                                    z.write(tfile.name, export_filename)

                                send_file = open(zfile.name, 'rb')
                                response = HttpResponse(send_file, content_type='application/zip')
                                response['Content-Disposition'] = 'attachment; filename=%s' % attachment_filename
                                return response
                            else:
                                flash(request, 'There are no available GTIN numbers for current active prefix', 'danger')
                        except Exception as e:
                            flash(request, 'Error: %s' % str(e), 'danger')
        else:
            flash(request, 'You must choose a prefix and an action!', 'danger')

    form = PrefixActionForm()
    form.fields['select_prefix'].choices = [(str(p.id), p.prefix) for p in prefixes]
    try:
        selected_prefix = int(request.POST['select_prefix'])
        prefix_service.make_active(selected_prefix)
    except:
        selected_prefix = prefix_service.get_active(company_organisation)

    config = {'GS1_GLN_CAPABILITY': settings.GS1_GLN_CAPABILITY}

    context = {
        'current_user': current_user,
        'config': config,
        'prefixes': prefixes,
        'susp_prefixes': susp_prefixes,
        'flashed_messages': flash_get_messages(request),
        'selected_prefix': selected_prefix
    }
    return render(request, 'prefixes/prefixes_list.html', context)


def prefixes_set_starting(request, prefix_id):
    current_user = users_service.get(1)
    prefix = prefix_service.find_item(id=prefix_id)
    if not prefix:
        Http404()
    sn_length = 12 - len(prefix.prefix)
    if request.method == 'POST':
        error = 'Incorrect entry. Please enter a valid number'
        form = StartingNumberForm(request.POST)
        if form.is_valid():
            if len(form.data['starting_number']) == sn_length:
                try:
                    int(form.data['starting_number'])
                except (ValueError, TypeError):
                    pass
                else:
                    starting_number = normalize('EAN13', prefix.prefix + form.data['starting_number'])
                    products = product_service.find(gtin="0" + starting_number, owner=current_user).all()
                    if len(products) == 0:
                        prefix.starting_from = starting_number
                        prefix_service.save(prefix)
                        flash(request, 'Starting gtin has been set to GTIN-%s' % prefix.starting_from, 'success')
                        return redirect(reverse('prefixes:prefixes_list'))
                    else:
                        error = 'This number is already assigned. Try another one.'
        flash(request, error, 'danger')
    form = StartingNumberForm()
    if not prefix.starting_from:
        try:
            prefix.make_starting_from()
        except:
            return render(request, 'prefixes/prefix_exhausted.html',
                                   {'current_user': current_user, 'prefix': prefix})
        prefix_service.save(prefix)
    form.data['starting_number'] = prefix.starting_from[len(prefix.prefix):12]
    context = { 'current_user': current_user,
                'prefix': prefix,
                'form': form,
                'current': prefix.starting_from,
                'sn_length': sn_length,
                'flashed_messages': flash_get_messages(request) }
    return render(request, 'prefixes/set_starting.html', context=context)


def jsonify(**kwargs):
    content = json.dumps(kwargs)
    response = HttpResponse(content, content_type='application/json')
    response['Content-Length'] = len(content)
    return response

prefixes/templates/prefixes/_location_prefix_list.html
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Your prefixes
            </div>
            <div class="panel-body">
                <form method="POST">{{ form.csrf_token }}
                    <p>Select a number bank from the list below, select the desired action and press the
                        Continue
                        button.</p>
                    <table class="table table-condensed table-striped">
                        <thead>
                        <th>Select</th>
                        <th>Prefix Description</th>
                        <th>Range</th>
                        <th>Next number</th>
                        <th>Locations</th>
                        </thead>
                        <tbody>
                        {% for prefix in prefixes %}
                            <tr>
                                <td><input type="radio" name="select_prefix" value="{{ prefix.id }}"
                                           {% if prefix.id == selected_prefix %}checked{% endif %}></td>
                                <td>
                                    <a href="#" class="prefix-editable" data-type="text"
                                       data-pk="{{ prefix.id }}"
                                       data-url="/prefixes/ajax/"
                                       data-title="Prefix Description"
                                    >{% if prefix.description %}{{ prefix.description }}{% else %}Block of {{ prefix.get_capacity }} GLNs{% endif %}</a>
                                </td>
                                <td>{% include 'prefixes/range_macros.html' with func='render_range' prefix=prefix only %}</td>
                                <td>{% include 'prefixes/range_macros.html' with func='render_starting_number' prefix=prefix only %}</td>
                                <td>{% if not prefix.locations %}
                                    No locations
                                {% else %}
                                    <a href="{% url 'user:locations.locations_list' %}?prefix={{ prefix.prefix }}">{{ prefix.locations }}
                                        Location{{ prefix.locations|pluralize }}</a>
                                {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="well col-md-12">
                        <h4>Actions</h4>
                        <ul class="list-unstyled" id="prefix-actions">
                            <li><input type="radio" name="prefix_action" value="new_gln">&nbsp;
                                {{ _("Enter a new location in selected range") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="set_gln">&nbsp;
                                {{ _("Set selected range as active and go to My Locations") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="starting_gln">&nbsp;
                                {{ _("Set starting GLN in selected range manually") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="first_available_gln">&nbsp;
                                {{ _("Set starting GLN to first available number") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="export_available_gln">&nbsp;
                                {{ _("Export available GLNs in this range") }}
                            </li>
                        </ul>
                        <button type="submit" class="btn btn-primary">
                            {{ _("Continue") }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

prefixes/templates/prefixes/_product_prefix_list.html
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Your prefixes
            </div>
            <div class="panel-body">
                <form method="POST">
                    {% csrf_token %}
                    <p>Select a number bank from the list below, select the desired action and press the
                        Continue
                        button.</p>
                    <table class="table table-condensed table-striped">
                        <thead>
                        <th>Select</th>
                        <th>Prefix Description</th>
                        <th>Range</th>
                        <th>Next number</th>
                        <th>Products</th>
                        </thead>
                        <tbody>
                        {% for prefix in prefixes %}
                            <tr>
                                <td><input type="radio" name="select_prefix" value="{{ prefix.id }}"
                                           {% if prefix.id == selected_prefix %}checked{% endif %}></td>
                                <td>
                                    <a href="#" class="prefix-editable"
                                       data-type="text"
                                       data-pk="{{ prefix.id }}"
                                       data-url="/prefixes/ajax/"
                                       data-title="Prefix Description"
                                    >{% if prefix.description %}{{ prefix.description }}{% else %}Block of {{ prefix.get_capacity }} GTINs{% endif %}</a>
                                </td>
                                <td>{% include 'prefixes/range_macros.html' with func='render_range' prefix=prefix only %}</td>
                                <td>{% include 'prefixes/range_macros.html' with func='render_starting_number' prefix=prefix only %}</td>
                                <td>{% if not prefix.products %}
                                    No products
                                {% else %}
                                    <a href="{% url 'products.products_list' %}?prefix={{ prefix.prefix }}">{{ prefix.products }}
                                        Product{{ prefix.products|pluralize }}</a>
                                {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="well col-md-12">
                        <h4>Actions</h4>
                        <ul class="list-unstyled" id="prefix-actions">
                            <li><input type="radio" name="prefix_action" value="new_product">&nbsp;
                                {{ _("Enter a new product in selected range") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="set_this">&nbsp;
                                {{ _("Set selected range as active and go to My Products") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="starting_gtin">&nbsp;
                                {{ _("Set starting GTIN in selected range manually") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="first_available">&nbsp;
                                {{ _("Set starting GTIN to first available number") }}
                            </li>
                            <li><input type="radio" name="prefix_action" value="export_available">&nbsp;
                                {{ _("Export available GTINs in this range") }}
                            </li>
                        </ul>
                        <button type="submit" class="btn btn-primary" onclick="flash_message(this)">
                            {{ _("Continue") }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function flash_message(t) {
        if (t.form['prefix_action'].value=='export_available') {
            setTimeout( function() {
                            flash('Available GTINs have been exported', 'success')
                        }, 2000 )
        }
    }
</script>

prefixes/templates/prefixes/prefix_exhausted.html
{% extends 'base.html' %}
{% block title %}
    GS1 Ireland Barcode Manager: {{ _('Prefix management') }}
{% endblock %}
{% block breadcrumb %}
            <ol class="breadcrumb">
                <li><a href="{% url 'user:auth_profile' %}">{{ _("Home") }}</a></li>
                <li>Prefixes</li>
            </ol>
{% endblock %}
{% block page_title %}
    {{ _('Prefix management') }}
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-md-12">
            <h3>Prefix exhausted</h3>

            <p class="danger">
                This prefix <b>{{ prefix.prefix }}</b> is exhausted.
            </p>

            <p>
                You cannot use this prefix to allocate further numbers.
                Please select another of your prefixes to be the active prefix
                or licence an additional prefix from the <a href="http://www.gs1ie.org/Members-Area">Members Portal</a>
                on the GS1 Ireland website.
            </p>


        </div>
    </div>

{% endblock %}

prefixes/templates/prefixes/prefixes_list.html
{% extends "base.html" %}
{% block title %}
    GS1 Ireland Barcode Manager: {{ _('Prefix management') }}
{% endblock %}

{% block base_css %}
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jquery-editable/css/jquery-editable.css"
          rel="stylesheet"/>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'user:auth_profile' %}">{{ _("Home") }}</a></li>
        <li>Prefixes</li>
    </ol>
{% endblock %}
{% block page_title %}
    {{ _('Prefix management') }}
{% endblock %}

{% block page_content %}

    {% if config.GS1_GLN_CAPABILITY %}

        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#product_prefixes">Products</a></li>
            <li><a data-toggle="tab" href="#location_prefixes">Locations</a></li>
        </ul>

        <div class="tab-content">
            <div id="product_prefixes" class="tab-pane fade in active">
                {% include "prefixes/_product_prefix_list.html" %}

            </div>
            <div id="location_prefixes" class="tab-pane tab-pane fade">
                {% include "prefixes/_location_prefix_list.html" %}
            </div>
        </div>

    {% else %}
        <div id="product_prefixes" class="tab-pane fade in active">
            {% include "prefixes/_product_prefix_list.html" %}
        </div>
    {% endif %}

    {% if susp_prefixes %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Suspended prefixes
                    </div>
                    <div class="panel-body">
                        <table class="table table-condensed table-striped">
                            <thead>
                            <th>Range</th>
                            <th>Status</th>
                            </thead>
                            <tbody>
                            {% for sp in susp_prefixes %}
                                <tr>
                                    <td>{{ sp.prefix }}</td>
                                    <td>Suspended
                                        {% if sp.is_special == 'READ-ONLY' %}
                                            - Read only prefix
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="well">
                            Contact GS1IE for information about activating again these prefixes.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block  base_scripts %}
    <script type='text/javascript'>
        $(document).ready(function () {
            $.fn.editable.defaults.mode = 'popup';
        })
        $(document).ready(function () {
            $('.prefix-editable').editable({ params : { csrfmiddlewaretoken : '{{ csrf_token }}' } });
        });
    </script>
{% endblock base_scripts %}

prefixes/templates/prefixes/range_macros.html
{% if func == 'render_range' %}
    {% with prefix.get_range as range %}
        {% with prefix.prefix|length as plength %}
            {% if prefix.is_upc %}
                <b>{% for i in range.0 %}{% if forloop.counter0 >= 1 %}{% if forloop.counter0 == plength %}</b><span style="color:#F26334">{% elif forloop.counter0 == 12 %}</span>{% endif %}{{ i }}{% endif %}{% endfor %}
                -
                <b>{% for i in range.1 %}{% if forloop.counter0 >= 1 %}{% if forloop.counter0 == plength %}</b><span style="color:#F26334">{% elif forloop.counter0 == 12 %}</span>{% endif %}{{ i }}{% endif %}{% endfor %}
            {% else %}
                <b>{% for i in range.0 %}{% if forloop.counter0 == plength %}</b><span style="color:#F26334">{% elif forloop.counter0 == 12 %}</span>{% endif %}{{ i }}{% endfor %}
                -
                <b>{% for i in range.1 %}{% if forloop.counter0 == plength %}</b><span style="color:#F26334">{% elif forloop.counter0 == 12 %}</span>{% endif %}{{ i }}{% endfor %}
            {% endif %}
        {% endwith %}
    {% endwith %}
{% elif func == 'render_starting_number' %}
    {% with prefix.starting_from as sf %}
        {% with prefix.prefix|length as plength %}
            {% if prefix.is_upc %}
                <b>{% for i in sf %}{% if forloop.counter0 >= 1 %}{% if forloop.counter0 == plength %}</b><span style="color:#F26334">{% elif forloop.counter0 == 12 %}</span>{% endif %}{{ i }}{% endif %}{% endfor %}
            {% else %}
                <b>{% for i in sf %}{% if forloop.counter0 == plength %}</b><span style="color:#F26334">{% elif forloop.counter0 == 12 %}</span>{% endif %}{{ i }}{% endfor %}
            {% endif %}
        {% endwith %}
    {% endwith %}
{% elif func == 'render_prefix' %}
    {% with prefix.prefix|length as plength %}
        {% if prefix.is_upc %}
            {% for i in prefix.prefix %}{% if forloop.counter0 >= 1 %}{{ i }}{% endif %}{% endfor %}
        {% else %}
            {{ prefix.prefix }}
        {% endif %}
    {% endwith %}
{% endif %}